In [2]:
import pandas as pd
import numpy as np


data = pd.read_csv('weekly_deaths.csv')
data.head()

,country,region,region_code,start_date,end_date,days,year,week,population,total_deaths,covid_deaths,expected_deaths,excess_deaths,non_covid_deaths,covid_deaths_per_100k,excess_deaths_per_100k,excess_deaths_pct_change
0,Australia,Australia,0,2020-01-01,2020-01-07,7,2020,1,25734100,2497,0.0,2463.111657,33.888343,2497.0,0.0,0.131687,0.013758
1,Australia,Australia,0,2020-01-08,2020-01-14,7,2020,2,25734100,2510,0.0,2458.278324,51.721676,2510.0,0.0,0.200985,0.021040
2,Australia,Australia,0,2020-01-15,2020-01-21,7,2020,3,25734100,2501,0.0,2436.444991,64.555009,2501.0,0.0,0.250854,0.026496
3,Australia,Australia,0,2020-01-22,2020-01-28,7,2020,4,25734100,2597,0.0,2436.611657,160.388343,2597.0,0.0,0.623252,0.065824
4,Australia,Australia,0,2020-01-29,2020-02-04,7,2020,5,25734100,2510,0.0,2425.944991,84.055009,2510.0,0.0,0.326629,0.034648

In [3]:
data.dropna()

,country,region,region_code,start_date,end_date,days,year,week,population,total_deaths,covid_deaths,expected_deaths,excess_deaths,non_covid_deaths,covid_deaths_per_100k,excess_deaths_per_100k,excess_deaths_pct_change
0,Australia,Australia,0,2020-01-01,2020-01-07,7,2020,1,25734100,2497,0.0,2463.111657,33.888343,2497.0,0.000000,0.131687,0.013758
1,Australia,Australia,0,2020-01-08,2020-01-14,7,2020,2,25734100,2510,0.0,2458.278324,51.721676,2510.0,0.000000,0.200985,0.021040
2,Australia,Australia,0,2020-01-15,2020-01-21,7,2020,3,25734100,2501,0.0,2436.444991,64.555009,2501.0,0.000000,0.250854,0.026496
3,Australia,Australia,0,2020-01-22,2020-01-28,7,2020,4,25734100,2597,0.0,2436.611657,160.388343,2597.0,0.000000,0.623252,0.065824
4,Australia,Australia,0,2020-01-29,2020-02-04,7,2020,5,25734100,2510,0.0,2425.944991,84.055009,2510.0,0.000000,0.326629,0.034648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11710,United States,United States,USA,2021-03-14,2021-03-20,7,2021,11,317812460,58076,7022.0,58898.357322,-822.357322,51054.0,2.209479,-0.258756,-0.013962
11711,United States,United States,USA,2021-03-21,2021-03-27,7,2021,12,317812460,57996,6938.0,58534.957322,-538.957322,51058.0,2.183048,-0.169583,-0.009207
11712,United States,United States,USA,2021-03-28,2021-04-03,7,2021,13,316020313,55007,9514.0,57810.357322,-2803.357322,45493.0,3.010566,-0.887081,-0.048492
11713,United States,United States,USA,2021-04-04,2021-04-10,7,2021,14,316020313,55265,6684.0,57736.557322,-2471.557322,48581.0,2.115054,-0.782088,-0.042807
11714,United States,United States,USA,2021-04-11,2021-04-17,7,2021,15,316020313,50995,4966.0,57356.757322,-6361.757322,46029.0,1.571418,-2.013085,-0.110916

In [4]:
data.isnull()

,country,region,region_code,start_date,end_date,days,year,week,population,total_deaths,covid_deaths,expected_deaths,excess_deaths,non_covid_deaths,covid_deaths_per_100k,excess_deaths_per_100k,excess_deaths_pct_change
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11710,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11711,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11712,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11713,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11714,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
data.isnull().count()

country                     11715
region                      11715
region_code                 11715
start_date                  11715
end_date                    11715
days                        11715
year                        11715
week                        11715
population                  11715
total_deaths                11715
covid_deaths                11715
expected_deaths             11715
excess_deaths               11715
non_covid_deaths            11715
covid_deaths_per_100k       11715
excess_deaths_per_100k      11715
excess_deaths_pct_change    11715
dtype: int64

In [8]:
data.drop_duplicates()

,country,region,region_code,start_date,end_date,days,year,week,population,total_deaths,covid_deaths,expected_deaths,excess_deaths,non_covid_deaths,covid_deaths_per_100k,excess_deaths_per_100k,excess_deaths_pct_change
0,Australia,Australia,0,2020-01-01,2020-01-07,7,2020,1,25734100,2497,0.0,2463.111657,33.888343,2497.0,0.000000,0.131687,0.013758
1,Australia,Australia,0,2020-01-08,2020-01-14,7,2020,2,25734100,2510,0.0,2458.278324,51.721676,2510.0,0.000000,0.200985,0.021040
2,Australia,Australia,0,2020-01-15,2020-01-21,7,2020,3,25734100,2501,0.0,2436.444991,64.555009,2501.0,0.000000,0.250854,0.026496
3,Australia,Australia,0,2020-01-22,2020-01-28,7,2020,4,25734100,2597,0.0,2436.611657,160.388343,2597.0,0.000000,0.623252,0.065824
4,Australia,Australia,0,2020-01-29,2020-02-04,7,2020,5,25734100,2510,0.0,2425.944991,84.055009,2510.0,0.000000,0.326629,0.034648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11710,United States,United States,USA,2021-03-14,2021-03-20,7,2021,11,317812460,58076,7022.0,58898.357322,-822.357322,51054.0,2.209479,-0.258756,-0.013962
11711,United States,United States,USA,2021-03-21,2021-03-27,7,2021,12,317812460,57996,6938.0,58534.957322,-538.957322,51058.0,2.183048,-0.169583,-0.009207
11712,United States,United States,USA,2021-03-28,2021-04-03,7,2021,13,316020313,55007,9514.0,57810.357322,-2803.357322,45493.0,3.010566,-0.887081,-0.048492
11713,United States,United States,USA,2021-04-04,2021-04-10,7,2021,14,316020313,55265,6684.0,57736.557322,-2471.557322,48581.0,2.115054,-0.782088,-0.042807
11714,United States,United States,USA,2021-04-11,2021-04-17,7,2021,15,316020313,50995,4966.0,57356.757322,-6361.757322,46029.0,1.571418,-2.013085,-0.110916

In [14]:
data.start_date = pd.to_datetime(data.start_date)
data.end_date = pd.to_datetime(data.end_date)
data

,country,region_code,start_date,end_date,days,year,week,population,total_deaths,covid_deaths,expected_deaths,excess_deaths,non_covid_deaths,covid_deaths_per_100k,excess_deaths_per_100k,excess_deaths_pct_change
0,Australia,0,2020-01-01,2020-01-07,7,2020,1,25734100,2497,0.0,2463.111657,33.888343,2497.0,0.000000,0.131687,0.013758
1,Australia,0,2020-01-08,2020-01-14,7,2020,2,25734100,2510,0.0,2458.278324,51.721676,2510.0,0.000000,0.200985,0.021040
2,Australia,0,2020-01-15,2020-01-21,7,2020,3,25734100,2501,0.0,2436.444991,64.555009,2501.0,0.000000,0.250854,0.026496
3,Australia,0,2020-01-22,2020-01-28,7,2020,4,25734100,2597,0.0,2436.611657,160.388343,2597.0,0.000000,0.623252,0.065824
4,Australia,0,2020-01-29,2020-02-04,7,2020,5,25734100,2510,0.0,2425.944991,84.055009,2510.0,0.000000,0.326629,0.034648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11710,United States,USA,2021-03-14,2021-03-20,7,2021,11,317812460,58076,7022.0,58898.357322,-822.357322,51054.0,2.209479,-0.258756,-0.013962
11711,United States,USA,2021-03-21,2021-03-27,7,2021,12,317812460,57996,6938.0,58534.957322,-538.957322,51058.0,2.183048,-0.169583,-0.009207
11712,United States,USA,2021-03-28,2021-04-03,7,2021,13,316020313,55007,9514.0,57810.357322,-2803.357322,45493.0,3.010566,-0.887081,-0.048492
11713,United States,USA,2021-04-04,2021-04-10,7,2021,14,316020313,55265,6684.0,57736.557322,-2471.557322,48581.0,2.115054,-0.782088,-0.042807
11714,United States,USA,2021-04-11,2021-04-17,7,2021,15,316020313,50995,4966.0,57356.757322,-6361.757322,46029.0,1.571418,-2.013085,-0.110916

In [15]:
remove = 'days'
data.drop(remove, inplace=True, axis=1)
data

,country,region_code,start_date,end_date,year,week,population,total_deaths,covid_deaths,expected_deaths,excess_deaths,non_covid_deaths,covid_deaths_per_100k,excess_deaths_per_100k,excess_deaths_pct_change
0,Australia,0,2020-01-01,2020-01-07,2020,1,25734100,2497,0.0,2463.111657,33.888343,2497.0,0.000000,0.131687,0.013758
1,Australia,0,2020-01-08,2020-01-14,2020,2,25734100,2510,0.0,2458.278324,51.721676,2510.0,0.000000,0.200985,0.021040
2,Australia,0,2020-01-15,2020-01-21,2020,3,25734100,2501,0.0,2436.444991,64.555009,2501.0,0.000000,0.250854,0.026496
3,Australia,0,2020-01-22,2020-01-28,2020,4,25734100,2597,0.0,2436.611657,160.388343,2597.0,0.000000,0.623252,0.065824
4,Australia,0,2020-01-29,2020-02-04,2020,5,25734100,2510,0.0,2425.944991,84.055009,2510.0,0.000000,0.326629,0.034648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11710,United States,USA,2021-03-14,2021-03-20,2021,11,317812460,58076,7022.0,58898.357322,-822.357322,51054.0,2.209479,-0.258756,-0.013962
11711,United States,USA,2021-03-21,2021-03-27,2021,12,317812460,57996,6938.0,58534.957322,-538.957322,51058.0,2.183048,-0.169583,-0.009207
11712,United States,USA,2021-03-28,2021-04-03,2021,13,316020313,55007,9514.0,57810.357322,-2803.357322,45493.0,3.010566,-0.887081,-0.048492
11713,United States,USA,2021-04-04,2021-04-10,2021,14,316020313,55265,6684.0,57736.557322,-2471.557322,48581.0,2.115054,-0.782088,-0.042807
11714,United States,USA,2021-04-11,2021-04-17,2021,15,316020313,50995,4966.0,57356.757322,-6361.757322,46029.0,1.571418,-2.013085,-0.110916